#!/usr/bin/env python3
"""Derive a bot config from the questionnaire, so exploration survives the
screeners instead of taking the first option into a terminate.

    python3 outline/gen_config.py outline/outline-spec.json outline/survey-config.json

For every [Terminate ...] rule the qualifying answers are pinned: a single
qualifying option becomes a `fixed` rule, several become an `options` rule so
the bot still branches across the answers that keep the interview alive. The
terminates themselves stay covered by outline/expected-paths.json, which
asserts each one fires.
"""
import json
import re
import sys

LETTERS = 'abcdefghijklmnopqrstuvwxyz'


def phrase(text, length=60):
    """A regex that recognises this question by its wording, robust to the
    small whitespace differences a live page introduces."""
    words = re.sub(r'[^\w ]', ' ', text).split()[:8]
    # Words are joined by "any punctuation/space", because the live page keeps
    # the commas this stripping removed.
    return r'\W+'.join(re.escape(w) for w in words)


def opt_regex(options):
    """Match any of these option labels, by their distinctive leading words."""
    parts = []
    for o in options:
        words = re.sub(r'[^\w ]', ' ', o['text']).split()[:4]
        if words:
            parts.append(r'\W+'.join(re.escape(w) for w in words))
    return '|'.join(parts)


def qualifying(rule, question):
    m = re.search(r'select\s+([a-z](?:\s*[-–]\s*[a-z])?(?:\s*,\s*[a-z])*)', rule['rule'], re.I)
    if not m:
        return []
    pool = [o['letter'] for o in question['options']]
    out = []
    for part in re.split(r'\s*,\s*', m.group(1)):
        ends = re.findall(r'[a-z]', part)
        if not ends or not all(e in pool for e in ends):
            continue
        if len(ends) > 1:
            out += pool[pool.index(ends[0]):pool.index(ends[-1]) + 1]
        else:
            out.append(ends[0])
    return [o for o in question['options'] if o['letter'] in out]


def main(spec_path, out_path):
    spec = json.load(open(spec_path))
    questions = {q['q']: q for q in spec['questions']}
    answers = []
    notes = []

    for rule in spec['rules']:
        if rule['type'] != 'terminate':
            continue
        q = questions[rule['q']]
        opts = qualifying(rule, q)
        if not opts:
            continue
        entry = {'match': phrase(q['text']), '_q': rule['q'], '_why': f"[Terminate {rule['rule']}]"}
        if len(opts) == 1:
            entry['fixed'] = phrase(opts[0]['text'], 40)
            notes.append(f"{rule['q']}: pinned to \"{opts[0]['text'][:40]}\" — the only answer that continues")
        else:
            entry['options'] = opt_regex(opts)
            notes.append(f"{rule['q']}: branching only across {', '.join(o['letter'] for o in opts)} — the answers that continue")
        answers.append(entry)

    config = {
        '_comment': 'Generated by outline/gen_config.py from the questionnaire. '
                    'Qualifying answers are pinned so exploration reaches the full flow; '
                    'the terminates themselves are asserted by outline/expected-paths.json.',
        '_derived': notes,
        'answers': answers,
        'delay': 400,
        'maxSteps': 200,
    }
    json.dump(config, open(out_path, 'w'), indent=2)
    print(f'{len(answers)} rule(s) -> {out_path}')
    for n in notes:
        print('  ', n)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'outline/outline-spec.json',
         sys.argv[2] if len(sys.argv) > 2 else 'outline/survey-config.json')
